version: '2'

services:
    web:
        build: ./server-container
        ports:
         - "5000:5000"
        networks:
            testing_net:
                ipv4_address: 172.18.0.21

    web1:
        build: ./camera-container
        networks:
            testing_net:
                ipv4_address: 172.18.0.22

networks:
    testing_net:
        ipam:
            config:
                - subnet: 172.18.0.0/16 
